### ISSUE TITLE
希望进一步优化

### ISSUE THREAD

**Issue by alian001** [iatmakdotcx/frida_war3#1]
我看了你的这个想法，挺好的，我有个工具，看了下，跟你的想法差不多，希望可以说说，这个执行函数的思路，

![2024-07-06_131050](https://github.com/iatmakdotcx/frida_war3/assets/36040293/7c7985e8-bbbe-4851-adf5-2081000543b9)

**Comment by alian001** [comment]
希望可以，加一个安装使用的教程，

**Comment by alian001** [comment]
pip install frida
pip install frida-tools

报错

C:\pyproject\frida_war3-main\frida_war3-main>python aa.py
Traceback (most recent call last):
  File "C:\pyproject\frida_war3-main\frida_war3-main\aa.py", line 26, in <module>
    main('War3.exe')
  File "C:\pyproject\frida_war3-main\frida_war3-main\aa.py", line 11, in main
    session = frida.attach(target_process)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 1193, in _pid_of
    return self.get_process(target).pid
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 969, in get_process
    raise _frida.ProcessNotFoundError(f"unable to find process with name '{process_name}'")
frida.ProcessNotFoundError: unable to find process with name 'War3.exe'
